### ISSUE TITLE
404 Response while setting up labels

### ISSUE THREAD

**Issue by Ayushd70** [azu/github-label-setup#12] opened 2021-07-30 14:50 UTC
For some reason there is a 404 response while setting up the labels.
using command:

> github-label-setup --token xxxx  --labels @kazupon/github-label-preset

Attached here is the complete console output https://katb.in/tail5386

**Comment by azu** [comment] 2021-07-30 23:06
Probably, related to #6

**Comment by azu** [comment] 2021-07-30 23:13
You need to install this package before setup.
```
npm install -g @kazupon/github-label-preset
github-label-setup --labels @kazupon/github-label-preset
```

close this issue as duplicate of #6

**Closed as completed by azu** 2021-07-30 23:13 UTC
Labels: duplicate
